name: "Action Man Github Action"
description: "Notify Action Man Dashboard"
inputs:
  public_vapid_key:
    description: "Your public VAPID key"
    required: true
  private_vapid_key:
    description: "Your private VAPID key"
    required: true
  subscription:
    description: "Your subscription"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
